
[functions.notify_application]
enabled = true
verify_jwt = true
import_map = "./functions/notify_application/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify_application/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify_application/*.html" ]

[functions.send_digest_17_oct]
enabled = true
verify_jwt = true
import_map = "./functions/send_digest_17_oct/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_digest_17_oct/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_digest_17_oct/*.html" ]

[functions.send_digest_17_ct]
enabled = true
verify_jwt = true
import_map = "./functions/send_digest_17_ct/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send_digest_17_ct/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send_digest_17_ct/*.html" ]
